language: rust
sudo: false

rust: nightly

env:
  global:
    - RUST_LINT_VERSION=nightly-2019-02-04
    - RUST_TOOLCHAINS="1.20.0 stable beta $RUST_LINT_VERSION nightly"

before_script: |
  ( set -o errexit;set -o pipefail; set -o xtrace;set -o nounset;
    for RUST_TOOLCHAIN in $RUST_TOOLCHAINS; do travis_retry rustup toolchain add $RUST_TOOLCHAIN; done
    travis_retry rustup component add rustfmt-preview --toolchain $RUST_LINT_VERSION
    travis_retry rustup component add clippy-preview --toolchain $RUST_LINT_VERSION
  )

script: |
  ( set -o errexit;set -o pipefail; set -o xtrace;set -o nounset;
    for RUST_TOOLCHAIN in $RUST_TOOLCHAINS; do (
      cargo +$RUST_TOOLCHAIN test --all-features
    ); done
    cargo +$RUST_LINT_VERSION fmt -- --check
    cargo +$RUST_LINT_VERSION clippy --all-targets --all-features -- -D warnings
    cargo +$RUST_LINT_VERSION doc --no-deps --all-features
  )

notifications:
  email: false
